---
##############################################################################
# Play 1 - Create new host in-memory inventory
##############################################################################
- name: Set facts for new host
  hosts: localhost
  tasks:
    - name: Adding new host to the inventory
      add_host:
        hostname: "{{ host_name|default('load_vm') }}"
        ansible_host: "{{ host_ip }}"
        ansible_port: "{{ host_port|default(22) }}"
        groups: just_created

##############################################################################
# Play 2 - Configure node from in-memory inventory
##############################################################################

- name: Configure node from in-memory inventory
  hosts: just_created
  remote_user: vagrant
  become: no
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Set password for the host
      set_fact:
        ansible_ssh_pass: "{{ host_pass|default('vagrant') }}"
    - name: "Wait for SSH banners"
      local_action: wait_for port="{{ ansible_port }}" host="{{ host_ip }}" search_regex=OpenSSH delay=5
      become: False
    - name: Update YCSB configuration file
      template: src=templates/ycsb_status.properties.j2 dest=/home/vagrant/ycsb/status.properties 
    - name: Update GATLING configuration file
      template: src=templates/gatling.conf.j2 dest=/home/vagrant/gatling/conf/gatling.conf
    - name: Update Downtimer script
      template: src=templates/run_downtimer.sh.j2 dest=/home/vagrant/run_downtimer.sh    
    - name: Setup NTP
      command: sudo ntpdate 80.240.216.155
    - name: Start load script
      command: /home/vagrant/start_tmux_sessions.sh

#    - name: Pause play to interact with the servers
#      pause: prompt="Playbook paused... hit <enter> to continue or <ctrl-c a> to abort"
